# Generated by Django 5.2.4 on 2025-07-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='decription',
            new_name='description',
        ),
    ]
