# Generated by Django 6.0 on 2025-12-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='details_en',
            field=models.TextField(blank=True, null=True, verbose_name='English Details'),
        ),
        migrations.AddField(
            model_name='products',
            name='details_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Russian Details'),
        ),
    ]
