# Generated by Django 6.0 on 2025-12-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Image'),
        ),
    ]
