# Generated by Django 6.0 on 2025-12-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_image_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='English Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Russian Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_en',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='Engilsh Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ru',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Russian Name'),
        ),
    ]
