# Generated by Django 6.0 on 2025-12-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_details_en_products_details_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='primary_color_en',
            field=models.CharField(default='', max_length=60, verbose_name='English Primary Color'),
        ),
        migrations.AlterField(
            model_name='products',
            name='primary_color_ru',
            field=models.CharField(default='', max_length=60, verbose_name='Russian Primary Color'),
        ),
    ]
