# Generated by Django 6.0 on 2025-12-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_products_primary_color_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='random_order',
            field=models.FloatField(db_index=True, default=0, verbose_name='Random Order'),
        ),
    ]
