# Generated by Django 6.0 on 2025-12-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_products_random_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bestseller',
            field=models.BooleanField(default=False, verbose_name='Bestseller'),
        ),
    ]
