# Generated by Django 6.0 on 2025-12-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_products_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='New Product'),
        ),
    ]
