# Generated by Django 6.0 on 2025-12-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_products_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_new',
        ),
    ]
